version: "3"
services:
  ds:
    image: ds
    restart: always
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 208.67.222.222