channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::nodejs=17.9.0
  - conda-forge::pandas
  - conda-forge::scikit-learn
  - conda-forge::matplotlib
  - conda-forge::jupyterlab
  - conda-forge::python=3.9